# config-ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: devlake-config-ui
spec:
  selector:
    app: devlake-config-ui
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30004
  type: NodePort