# config-ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlake-config-ui
  labels:
    app: devlake-config-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devlake-config-ui
  template:
    metadata:
      labels:
        app: devlake-config-ui
    spec:
      containers:
      - name: config-ui
        image: apache/devlake-config-ui:v1.0.2-beta5
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: devlake-config
              key: CONFIG_UI_PORT
        - name: LAKE_API_URL
          value: "http://devlake-lake:8080"
