# grafana-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: devlake-grafana
spec:
  selector:
    app: devlake-grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30003
  type: NodePort