# grafana-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlake-grafana
  labels:
    app: devlake-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devlake-grafana
  template:
    metadata:
      labels:
        app: devlake-grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.2.0
        ports:
        - containerPort: 3000
        env:
        - name: GF_SERVER_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: devlake-config
              key: GRAFANA_PORT
