# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlake-postgres
  labels:
    app: devlake-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devlake-postgres
  template:
    metadata:
      labels:
        app: devlake-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "devlake"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devlake-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: "lake"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: devlake-postgres-pvc
